### ISSUE TITLE
SyntaxError : Non-ASCII character '\xc3'

### ISSUE THREAD

**Issue by Artur21** [conix-security/bl2ru2#1]
Getting syntax error when trying to create rules
root # python bl2ru2.py blacklist.txt -o cert-conix.rules
Error:
File "bl2ru2.py", line 2
SyntaxError: Non-ASCII character '\xc3' in file bl2ru2.py on line 2, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

**Comment by rmarsollier** [comment]
Try running it with python3, should work.
Sorry, README wasn't clear about that.
